//! CKB/Molecule call shapes, with monomorphized codecs and identical output.
//! Input preparation and reference checks are outside the timer. Allocation,
//! formatting, Serde and output destruction are included where the caller uses them.
//!
//! Source audit: CKB develop 95fd03933ce2a396b84aed12caaa0f984165cd6c;
//! Molecule master e2895756b66bc4935a31a2fa13420d869cc6c511 (bindings 0.9.2).
//! Both currently select faster-hex 0.6.1, included as `legacy_0_6`.
//! CKB: util/fixed-hash/core/src/serde.rs; util/jsonrpc-types/src/{fixed_bytes,
//! proposal_short_id,bytes,pool}.rs. The two RPC serialization stages come from
//! jsonrpc-utils-macros 0.3.0 and jsonrpc-core 18.0.0. Only serialization is timed,
//! excluding transaction-pool access, wire transport and conversion of packed types.
//! Molecule: bindings/rust/src/lib.rs and tools/codegen/src/generator/languages/
//! rust/display.rs. `molecule_display` writes the generated Bytes display shape
//! into reusable destination storage, including the temporary string it creates.
//! `faster_hex_borrowed` is a possible caller change, not today's Molecule behavior.
//! Both display variants retain the generated type's Display wrapper.
//!
//! These are isolated caller-shaped workloads, not full CKB benchmarks. H256
//! parsing/formatting uses CKB's own scalar code; Molecule without std does not
//! use faster-hex. DNS seeding's 64-byte public-key decode is currently disabled.
//! Those paths must not be credited with improvements measured here.
use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};
use fashex::Hex as _;
use hex_simd::{AsOut, AsciiCase};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::{convert::TryInto, fmt, fmt::Write, hint::black_box, marker::PhantomData};

mod support;

trait Codec {
    const NAME: &'static str;
    fn encode(src: &[u8], dst: &mut [u8]) -> Result<(), ()>;
    fn decode(src: &[u8], dst: &mut [u8]) -> Result<(), ()>;
    fn string(src: &[u8]) -> String;
}

macro_rules! codec {
    ($ty:ident, $name:literal, $encode:expr, $decode:expr, $string:expr) => {
        struct $ty;
        impl Codec for $ty {
            const NAME: &'static str = $name;
            #[inline]
            fn encode(src: &[u8], dst: &mut [u8]) -> Result<(), ()> {
                $encode(src, dst)
            }
            #[inline]
            fn decode(src: &[u8], dst: &mut [u8]) -> Result<(), ()> {
                $decode(src, dst)
            }
            #[inline]
            fn string(src: &[u8]) -> String {
                $string(src)
            }
        }
    };
}

codec!(
    Current,
    "faster_hex",
    |s, d| faster_hex::hex_encode(s, d).map(|_| ()).map_err(|_| ()),
    |s, d| faster_hex::hex_decode(s, d).map(|_| ()).map_err(|_| ()),
    faster_hex::hex_string
);
codec!(
    Legacy,
    "legacy_0_6",
    |s, d| faster_hex_legacy::hex_encode(s, d).map_err(|_| ()),
    |s, d| faster_hex_legacy::hex_decode(s, d).map_err(|_| ()),
    faster_hex_legacy::hex_string
);
codec!(
    ConstHex,
    "const_hex",
    |s, d| const_hex::encode_to_str(s, d).map(|_| ()).map_err(|_| ()),
    |s, d| const_hex::decode_to_slice(s, d).map_err(|_| ()),
    const_hex::encode
);
codec!(
    HexSimd,
    "hex_simd",
    |s, d: &mut [u8]| {
        let _ = hex_simd::encode(s, d.as_out(), AsciiCase::Lower);
        Ok(())
    },
    |s, d: &mut [u8]| hex_simd::decode(s, d.as_out()).map(|_| ()).map_err(|_| ()),
    |s| hex_simd::encode_to_string(s, AsciiCase::Lower)
);
codec!(
    Fashex,
    "fashex",
    |s, d| fashex::encode::<false>(s, d).map(|_| ()).map_err(|_| ()),
    |s, d| fashex::decode(s, d).map(|_| ()).map_err(|_| ()),
    |s: &[u8]| s.hex::<String, false>().unwrap()
);
codec!(
    BetterHex,
    "better_hex",
    |s, d| better_hex::encode_to_slice(s, d)
        .map(|_| ())
        .map_err(|_| ()),
    |s, d| better_hex::decode_to_slice(s, d)
        .map(|_| ())
        .map_err(|_| ()),
    |s| better_hex::encode(s).unwrap()
);

// CKB uses [u8; 2*N+2] on the stack, with two bytes reserved for "0x".
// M is explicit because generic const expressions are not needed by this crate.
struct Fixed<C, const N: usize, const M: usize>([u8; N], PhantomData<C>);

impl<C: Codec, const N: usize, const M: usize> Serialize for Fixed<C, N, M> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut output = [0; M];
        output[..2].copy_from_slice(b"0x");
        C::encode(&self.0, &mut output[2..]).map_err(|()| serde::ser::Error::custom("hex"))?;
        // SAFETY: All encoders write ASCII to the exact payload slice on success.
        serializer.serialize_str(unsafe { std::str::from_utf8_unchecked(&output) })
    }
}

// This is the Byte32/ProposalShortId input path. CKB's H256 FromStr has its own
// scalar parser and is deliberately not represented as a faster-hex decoder.
impl<'de, C: Codec, const N: usize, const M: usize> Deserialize<'de> for Fixed<C, N, M> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct Visitor<C, const N: usize, const M: usize>(PhantomData<C>);
        impl<C: Codec, const N: usize, const M: usize> serde::de::Visitor<'_> for Visitor<C, N, M> {
            type Value = Fixed<C, N, M>;
            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("a fixed-length 0x-prefixed hex string")
            }
            fn visit_str<E: serde::de::Error>(self, value: &str) -> Result<Self::Value, E> {
                if value.len() != M || !value.starts_with("0x") {
                    return Err(E::custom("hex length or prefix"));
                }
                let mut bytes = [0; N];
                C::decode(&value.as_bytes()[2..], &mut bytes).map_err(|()| E::custom("hex"))?;
                Ok(Fixed(bytes, PhantomData))
            }
        }
        deserializer.deserialize_str(Visitor(PhantomData))
    }
}

fn fixed<C: Codec, const N: usize, const M: usize>(c: &mut Criterion) {
    assert_eq!(M, N * 2 + 2);
    let bytes = support::bytes(N * 256);
    let values: Vec<Fixed<C, N, M>> = bytes
        .chunks_exact(N)
        .map(|s| Fixed(s.try_into().unwrap(), PhantomData))
        .collect();
    let expected: Vec<_> = values
        .iter()
        .map(|v| format!("\"0x{}\"", hex::encode(v.0)))
        .collect();
    for (v, expected) in values.iter().zip(&expected) {
        assert_eq!(serde_json::to_string(v).unwrap(), *expected);
    }
    let mut group = c.benchmark_group("ckb_fixed_json");
    let mut cursor = 0;
    group.bench_function(BenchmarkId::new(C::NAME, N), |b| {
        b.iter(|| {
            let value = &values[cursor];
            cursor = (cursor + 1) & 255;
            black_box(serde_json::to_string(black_box(value)).unwrap())
        })
    });
    group.finish();

    let mut group = c.benchmark_group("ckb_fixed_buffer");
    group.bench_function(BenchmarkId::new(C::NAME, N), |b| {
        b.iter(|| {
            let value = black_box(&values[cursor]);
            cursor = (cursor + 1) & 255;
            let mut output = [0; M];
            output[..2].copy_from_slice(b"0x");
            C::encode(&value.0, &mut output[2..]).unwrap();
            black_box(output)
        });
    });
    group.finish();

    if N == 10 || N == 32 {
        for (expected, original) in expected.iter().zip(&values) {
            assert_eq!(
                serde_json::from_str::<Fixed<C, N, M>>(expected).unwrap().0,
                original.0
            );
        }
        let mut group = c.benchmark_group("ckb_fixed_parse");
        group.bench_function(BenchmarkId::new(C::NAME, N), |b| {
            b.iter(|| {
                let text = &expected[cursor];
                cursor = (cursor + 1) & 255;
                black_box(
                    serde_json::from_str::<Fixed<C, N, M>>(black_box(text))
                        .unwrap()
                        .0,
                )
            })
        });
        group.finish();
    }
}

#[derive(Serialize)]
struct Pool<'a, T> {
    pending: &'a [T],
    proposed: &'a [T],
}

#[derive(Serialize)]
struct Response {
    jsonrpc: &'static str,
    result: serde_json::Value,
    id: u64,
}

fn pool<C: Codec>(c: &mut Criterion) {
    let bytes = support::bytes(32 * 256);
    let values: Vec<Fixed<C, 32, 66>> = bytes
        .chunks_exact(32)
        .map(|s| Fixed(s.try_into().unwrap(), PhantomData))
        .collect();
    for count in [1, 256] {
        let pool = Pool {
            pending: &values[..count],
            proposed: &[],
        };
        let expected = serde_json::json!({
            "pending": values[..count].iter().map(|v| format!("0x{}", hex::encode(v.0))).collect::<Vec<_>>(),
            "proposed": [],
        });
        assert_eq!(serde_json::to_value(&pool).unwrap(), expected);
        let mut group = c.benchmark_group("ckb_pool_value");
        group.bench_function(BenchmarkId::new(C::NAME, count), |b| {
            b.iter(|| black_box(serde_json::to_value(black_box(&pool)).unwrap()))
        });
        group.finish();
        // jsonrpc-utils converts the result to Value; jsonrpc-core then writes
        // the response as JSON. No network, pool lookup or transaction conversion.
        let mut group = c.benchmark_group("ckb_pool_rpc");
        group.bench_function(BenchmarkId::new(C::NAME, count), |b| {
            b.iter(|| {
                let response = Response {
                    jsonrpc: "2.0",
                    result: serde_json::to_value(black_box(&pool)).unwrap(),
                    id: 1,
                };
                black_box(serde_json::to_string(&response).unwrap())
            })
        });
        group.finish();
    }
}

struct JsonBytes<C>(bytes::Bytes, PhantomData<C>);

impl<C: Codec> Serialize for JsonBytes<C> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut output = vec![0; self.0.len() * 2 + 2];
        output[..2].copy_from_slice(b"0x");
        C::encode(&self.0, &mut output[2..]).map_err(|()| serde::ser::Error::custom("hex"))?;
        // SAFETY: The prefix and successful encoder initialize the entire output as ASCII.
        serializer.serialize_str(unsafe { std::str::from_utf8_unchecked(&output) })
    }
}

impl<'de, C: Codec> Deserialize<'de> for JsonBytes<C> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct Visitor<C>(PhantomData<C>);
        impl<C: Codec> serde::de::Visitor<'_> for Visitor<C> {
            type Value = JsonBytes<C>;
            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("a 0x-prefixed hex string")
            }
            fn visit_str<E: serde::de::Error>(self, value: &str) -> Result<Self::Value, E> {
                let text = value
                    .strip_prefix("0x")
                    .ok_or_else(|| E::custom("hex prefix"))?;
                if !text.len().is_multiple_of(2) {
                    return Err(E::custom("hex length"));
                }
                if text.is_empty() {
                    return Ok(JsonBytes(bytes::Bytes::new(), PhantomData));
                }
                let mut bytes = vec![0; text.len() / 2];
                C::decode(text.as_bytes(), &mut bytes).map_err(|()| E::custom("hex"))?;
                Ok(JsonBytes(bytes.into(), PhantomData))
            }
        }
        deserializer.deserialize_str(Visitor(PhantomData))
    }
}

fn variable<C: Codec>(c: &mut Criterion) {
    for len in [0, 1, 32, 65, 256, 4096] {
        let value = JsonBytes::<C>(support::bytes(len).into(), PhantomData);
        let expected = format!("\"0x{}\"", hex::encode(&value.0));
        assert_eq!(serde_json::to_string(&value).unwrap(), expected);
        assert_eq!(
            serde_json::from_str::<JsonBytes<C>>(&expected).unwrap().0,
            value.0
        );
        let mut group = c.benchmark_group("ckb_bytes_json");
        group.bench_function(BenchmarkId::new(C::NAME, len), |b| {
            b.iter(|| black_box(serde_json::to_string(black_box(&value)).unwrap()))
        });
        group.finish();
        let mut group = c.benchmark_group("ckb_bytes_parse");
        group.bench_function(BenchmarkId::new(C::NAME, len), |b| {
            b.iter(|| {
                black_box(serde_json::from_str::<JsonBytes<C>>(black_box(&expected)).unwrap())
            })
        });
        group.finish();
    }
}

struct MoleculeDisplay<'a, C>(&'a [u8], PhantomData<C>);
impl<C: Codec> fmt::Display for MoleculeDisplay<'_, C> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Bytes(0x{})", C::string(self.0))
    }
}

struct MoleculeBorrowed<'a>(&'a [u8]);
impl fmt::Display for MoleculeBorrowed<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Bytes(0x{})", faster_hex::Hex::new(self.0))
    }
}

fn molecule<C: Codec>(c: &mut Criterion) {
    for len in [0, 1, 10, 20, 32, 64, 65, 256, 4096] {
        let bytes = support::bytes(len * 256);
        let input: Vec<&[u8]> = if len == 0 {
            vec![&[]; 256]
        } else {
            bytes.chunks_exact(len).collect()
        };
        for src in &input {
            assert_eq!(C::string(src), hex::encode(src));
        }
        let mut cursor = 0;
        let mut group = c.benchmark_group("molecule_string");
        group.bench_function(BenchmarkId::new(C::NAME, len), |b| {
            b.iter(|| {
                let src = input[cursor];
                cursor = (cursor + 1) & 255;
                black_box(C::string(black_box(src)))
            })
        });
        group.finish();

        let mut output = String::with_capacity(len * 2 + 16);
        for src in &input {
            assert_eq!(
                format!("{}", MoleculeDisplay::<C>(src, PhantomData)),
                format!("Bytes(0x{})", hex::encode(src))
            );
        }
        let mut group = c.benchmark_group("molecule_display");
        group.bench_function(BenchmarkId::new(C::NAME, len), |b| {
            b.iter(|| {
                let src = input[cursor];
                cursor = (cursor + 1) & 255;
                output.clear();
                write!(
                    output,
                    "{}",
                    MoleculeDisplay::<C>(black_box(src), PhantomData)
                )
                .unwrap();
                black_box(output.as_bytes());
            })
        });
        if C::NAME == Current::NAME {
            for src in &input {
                assert_eq!(
                    format!("{}", MoleculeBorrowed(src)),
                    format!("Bytes(0x{})", hex::encode(src))
                );
            }
            group.bench_function(BenchmarkId::new("faster_hex_borrowed", len), |b| {
                b.iter(|| {
                    let src = input[cursor];
                    cursor = (cursor + 1) & 255;
                    output.clear();
                    write!(output, "{}", MoleculeBorrowed(black_box(src))).unwrap();
                    black_box(output.as_bytes());
                })
            });
        }
        group.finish();
    }
}

fn cases<C: Codec>(c: &mut Criterion) {
    fixed::<C, 10, 22>(c); // ProposalShortId.
    fixed::<C, 20, 42>(c); // H160.
    fixed::<C, 32, 66>(c); // H256 / Byte32.
    fixed::<C, 64, 130>(c); // H512.
    fixed::<C, 65, 132>(c); // H520.
    pool::<C>(c);
    variable::<C>(c);
    molecule::<C>(c);
}

fn consumers(c: &mut Criterion) {
    cases::<Current>(c);
    cases::<Legacy>(c);
    cases::<ConstHex>(c);
    cases::<HexSimd>(c);
    cases::<Fashex>(c);
    cases::<BetterHex>(c);
}

criterion_group!(benches, consumers);
criterion_main!(benches);
